### ISSUE TITLE
フォントダウンロードのリクエストが失敗するエラー

### ISSUE THREAD

**Issue by Moriyuki-S** [Haruki65/CookMeet#11]
`npm run dev`したときに毎回このエラー出ます。

`Retrying 1/3...
request to https://fonts.gstatic.com/s/inter/v13/UcC73FwrK3iLTeHuS_fvQtMwCp50KnMa1ZL7W0Q5nw.woff2 failed, reason: `

**Comment by Haruki65** [comment]
私はそのエラーが出ないです、、なぜなのか気になります
