### ISSUE TITLE
layout.tsxのimportについて

### ISSUE THREAD

**Issue by Moriyuki-S** [Haruki65/CookMeet#12]
layout.tsxは配下の`tsx`に自動的に適用されるので、`<Layout></Layout>`で囲む必要はないと思います。これで囲まれてるページの開発者ツールよく見ると、`<main>`タグが2つあります。

**Comment by Haruki65** [comment]
勘違いをしていました。なのでヘッダーがたまに二重に表示されていたのですね。ご指摘ありがとうございます。
